name: RealTimeFolia
version: '1.1'
main: org.titago.RealTimeFolia
api-version: '1.21'
author: AMapeKiberT
description: A plugin to sync Minecraft time with real-world time per world.
license: AGPL-3.0
source: https://github.com/amapekibert/RealTimeFolia
folia-supported: true
commands:
  realtimefolia:
    description: Reload the plugin configuration
    usage: /realtimefolia reload
    permission: realtimefolia.reload
permissions:
  realtimefolia.reload:
    description: Allows reloading the plugin
    default: op